### Import Libraraies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

### Import Dataset

In [2]:
# dataset is dirctly downlaod from 
# https://www.kaggle.com/datasets/rupakroy/online-payments-fraud-detection-dataset?resource=download
data_set = pd.read_csv("Fraud_Detection_Data.csv")
print(data_set.head())

   step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig   
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36  \
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0  


#### Checking Dataset size

In [3]:
data_set.shape

(6362620, 11)

### Checking any Null value

In [4]:
print( data_set.isnull().sum())

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64


### Count total values in Type column

In [7]:
type=data_set.type.value_counts()
print( type)

type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64


#### Pie chart for Different transactions in Type Column

In [8]:
quantity=type.values
transactions= type.index
print(transactions, "\n" ,quantity)

Index(['CASH_OUT', 'PAYMENT', 'CASH_IN', 'TRANSFER', 'DEBIT'], dtype='object', name='type') 
 [2237500 2151495 1399284  532909   41432]


In [9]:
graph= px.pie(type,names=transactions,values=quantity, hole=0.4, title= "Distribution of Transaction types")
graph.show()

### Drop column 

In [10]:
data_set_1= data_set.drop(['step','nameOrig', 'nameDest','oldbalanceDest','newbalanceDest','isFlaggedFraud'], axis=1)
print(data_set_1.head())

       type    amount  oldbalanceOrg  newbalanceOrig  isFraud
0   PAYMENT   9839.64       170136.0       160296.36        0
1   PAYMENT   1864.28        21249.0        19384.72        0
2  TRANSFER    181.00          181.0            0.00        1
3  CASH_OUT    181.00          181.0            0.00        1
4   PAYMENT  11668.14        41554.0        29885.86        0


### Seperate the dependent and Independent values

In [12]:
X = data_set_1.iloc [ : , :-1 ].values  # independent values
Y = data_set_1.iloc [: , -1 ].values   # Dependent variable
print(X)
print(Y)

[['PAYMENT' 9839.64 170136.0 160296.36]
 ['PAYMENT' 1864.28 21249.0 19384.72]
 ['TRANSFER' 181.0 181.0 0.0]
 ...
 ['CASH_OUT' 6311409.28 6311409.28 0.0]
 ['TRANSFER' 850002.52 850002.52 0.0]
 ['CASH_OUT' 850002.52 850002.52 0.0]]
[0 0 1 ... 1 1 1]


### Encoding categorical data

In [13]:
# One hot Encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
CT= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])] , remainder='passthrough')
X = np.array(CT.fit_transform (X))

In [14]:
print(X)

[[0.0 0.0 0.0 ... 9839.64 170136.0 160296.36]
 [0.0 0.0 0.0 ... 1864.28 21249.0 19384.72]
 [0.0 0.0 0.0 ... 181.0 181.0 0.0]
 ...
 [0.0 1.0 0.0 ... 6311409.28 6311409.28 0.0]
 [0.0 0.0 0.0 ... 850002.52 850002.52 0.0]
 [0.0 1.0 0.0 ... 850002.52 850002.52 0.0]]


In [15]:
print(Y)

[0 0 1 ... 1 1 1]


#### spliting data int training and testing data

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split (X,Y, test_size= 0.2, random_state= 1)

### Apply ML Model "Decision Tree"

In [17]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,Y_train)


DecisionTreeClassifier(criterion='entropy', random_state=0)

#### Accuracy of Model

In [18]:
print(classifier.score(X_test, Y_test))

0.9996895932807555


### predict the value

In [19]:
prediction_value= np.array([[ 0.0, 0.0, 0.0,0.0, 0.0, 9839.64, 170136.0, 160296.36]])
print (classifier.predict(prediction_value))
# 0----> Fraud
# 1----> No fraud

[0]
